quartz:
  #相关属性配置
  auto-startup: true
  overwrite-existing-jobs: true
  properties:
    org:
      quartz:
        scheduler:
          instanceName: IsimClusteredScheduler
          instanceId: AUTO
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          tablePrefix: qrtz_
          isClustered: true
          clusterCheckinInterval: 50000
          useProperties: false
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 10
          threadPriority: 5
          threadsInheritContextClassLoaderOfInitializingThread: true
  #数据库方式
  job-store-type: jdbc
  #初始化表结构，初始使用值为always,然后将值改为never
  jdbc:
    initialize-schema: never

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    enabled: true
    max-connections: 100
  jms:
    pub-sub-domain: true