server:
  port: 8080
  context-path: /pro
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    pool:
      enabled: true
      max-connections: 10
#  jms:
#    pub-sub-domain: true
queueName: publish.queue
topicName: publish.topic