spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url1: jdbc:mysql://localhost:3306/db_example?serverTimezone=GMT%2B8
    url2: jdbc:mysql://localhost:3306/db_example2?serverTimezone=GMT%2B8
    username: springuser
    password: 123456