/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ThriftTest.tutorial;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class testConstants {

  /**
   * Thrift 还允许你定义用于跨语言的常量.
   * 复杂的类型和结构体可以通过json表示法进行指定.
   */
  public static final int INT32CONSTANT = 9853;

  public static final java.util.Map<java.lang.String,java.lang.String> MAPCONSTANT = new java.util.HashMap<java.lang.String,java.lang.String>();
  static {
    MAPCONSTANT.put("goodnight", "moon");
    MAPCONSTANT.put("hello", "world");
  }

}
